<a href="https://colab.research.google.com/github/RoCkEtToMaN/Python/blob/master/Sezione_12_Il_Calcolo_Scientifico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Sezione 12: Il Calcolo Scientifico***

Il modulo che si vedrà è de-facto che darà vita a Scikit-Learn, Tensorflow, Pandas ed altri che vengono utilizzati in ambito ML e AI:



* *Numpy*


Se si usa Anaconda, questo modulo dovrebbe essere già installato!



```
pip install numpy
```






##***Calcolo Scientifico con Numpy***

Questo modulo è veramente calcolato ad hoc per questo, ha a disposizione molte funzioni fatte con C e quindi sono molto veloci!

Come tutti i moduli, lo importiamo:


In [8]:
import numpy as np

Ora affrontiamo a vedere i:

####***I Vettori***

Il calcolo tra vettori e matrici è un qualcosa molto importante in tutti i linguaggi di programmazione!

I vettori possono essere di piu dimensioni e di piu tipi!

In [ ]:
l=[10,2,76,1,3]
v=np.array(l)

In [ ]:
print(v,type(v))

[10  2 76  1  3] <class 'numpy.ndarray'>


Vediamo che è di tipo array!

Se vogliamo accedere agli indici, vale sempre il discorso dell'indexing!



*  *Indexing*:




In [ ]:
v[0]

10

In [ ]:
v[1]

2

In [ ]:
v[-1]

3



*   *Slicing*: per ritagliare una parte di array




In [ ]:
v[1:3]

array([ 2, 76])

In [ ]:
v[:1]

array([10])

In [ ]:
v[-1:]

array([3])



*   *Maschere*: andiamo a mascherare valori che non rispettano alcuni vincoli




In [ ]:
mask = v >20

In [ ]:
v
mask

array([False, False,  True, False, False])

In [ ]:
v2=v[mask]
v2


array([76])

Questo passaggio lo si fa all'interno di un'unica operazione:

In [ ]:
v_lm=v[v<v.mean()]
v_lm

array([10,  2,  1,  3])

Se volessimo modificare gli elementi di un vettore:

*   *Modificare* elementi di un vettore:




In [ ]:
v=np.array([1,2,3,4,5])

In [ ]:
v

array([1, 2, 3, 4, 5])

Come con le liste:

In [ ]:
v[0]=10
v

array([10,  2,  3,  4,  5])

In [ ]:
v[:2]


array([10,  2])

In [ ]:
v[-2:]

array([4, 5])

In [ ]:
v[:2]=v[-2:]
v

array([4, 5, 3, 4, 5])

####***Operazioni sui Vettori***

Creiamo in primis due vettori:

In [ ]:
a=np.array([10,20,56,12,11])
b=np.array([6,1,3,88,53])

Per tutte queste operazioni, abbiamo visto come creare le classi per fare questo!
Limitiamoci ad utilizzare tutto ciò che è già pronto!

*   *Somma*: 




In [ ]:
c = a + b
print(c)

[ 16  21  59 100  64]


*   *Differenza*: 

In [ ]:
d=a-b
print(d)

[  4  19  53 -76 -42]


*   *Moltiplicazione*: 




> 1.  vettoriale:


In [ ]:
e=a*b
print(e)

[  60   20  168 1056  583]


> 2.  scalare:

In [ ]:
f=a.dot(b)
print(f)

1887


####***Operazioni su un singolo Vettore***

Definisco un vettore:


In [ ]:
v=np.array([1,2, 54,11, 43])
v

array([ 1,  2, 54, 11, 43])



*   *Eliminazione*: 




In [ ]:
v=np.delete(v,3)
v

array([ 1,  2, 54, 43])

Vediamo come possiamo andare a scegliere se eliminare la colonna o riga:

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr
np.delete(arr, 0, 1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

*   *Aggiunta*: 

In [ ]:
v=np.insert(v,3,13)
v

array([ 1,  2, 54, 13, 43])

oppure con:

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.concatenate((a, b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

*   *Shuffle*: modifica il vettore e quindi non ci deve essere un'assegnazione e va a posizionare in modo random i componenti del vettore





In [ ]:
v
np.random.shuffle(v)
v

array([13,  2, 43, 54,  1])

####***Funzioni Base***




*   *Len*: quanti elementi vi sono all'interno del vettore
*   *Sort*:va ad ordinare i componenti in ordine crescente
*   *Sum* : fa la somma degli elementi del vettore, dando uno scalare






####***Matrici con Numpy***

Insime di numeri disposti su piu righe e colonne.
Essendo un array bidimensionale:

In [ ]:
import numpy as np

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Vediamo quanti elementi ha dentro:

In [ ]:
m.size

9

Determiniamo il formato:

In [ ]:
m.shape

(3, 3)

Accedere agli elementi:

In [ ]:
m[1]

array([4, 5, 6])

In [ ]:
m[1,1]

5

In [ ]:
m[:-2,:2]

array([[1, 2]])

####***Ridimensionamento con Numpy***





Vediamo come procedere alla modifica:

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]




*   *reshape*:da (4x3) la vogliamo far diventare (3x4)




In [ ]:
m=m.reshape(3,4)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]




*   *flattering*: consiste nel mettere su un'unica riga una matrice:




In [ ]:
m_flatten1 =m.reshape(1,m.size)
print(m_flatten1)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


O in modo piu diretto:

In [ ]:
m_flatten2=m.flatten()

print(m_flatten2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Ma nel primo caso si ottiene una matrice 1x12 e lo si può notare dalla doppia parentesi.
Nel secondo caso, invece otteniamo un vettore vero e proprio!

Con Shape, lo dimostriamo!

####***Broadcasting e Operazioni tra Matrici***

Valgono gli stessi concetti degli array e possiamo utilizzare gli stessi operatori aritmetici:





In [3]:
import numpy as np

In [ ]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[7,12,35],[34,25,16],[57,98,90]])



*   *somma*:



In [ ]:
m1+m2

array([[  8,  14,  38],
       [ 38,  30,  22],
       [ 64, 106,  99]])



*   *differenza*:




In [ ]:
m1-m2

array([[ -6, -10, -32],
       [-30, -20, -10],
       [-50, -90, -81]])



*   *divisione valore per valore*:




In [ ]:
m1/m2

array([[0.14285714, 0.16666667, 0.08571429],
       [0.11764706, 0.2       , 0.375     ],
       [0.12280702, 0.08163265, 0.1       ]])



*   *prodotto valore per valore*:




In [ ]:
m1*m2

array([[  7,  24, 105],
       [136, 125,  96],
       [399, 784, 810]])

*   *prodotto scalare*:

In [ ]:
m3=np.array([[1,2],[6,7],[9,8]])

Classico modo extra numpy

In [ ]:
m1.dot(m3)

array([[ 40,  40],
       [ 88,  91],
       [136, 142]])

Utilizzando numpy

In [ ]:
np.dot(m1,m3)

array([[ 40,  40],
       [ 88,  91],
       [136, 142]])

####***Operazioni tra Vettori e Matrici***

Vediamo subito come questo modulo ci permette di fare:

In [ ]:
m = np.array([[4,5,9],[2,7,4],[7,9,8]])
v = np.array([9,2,5])

Vediamo che abbiamo una *Matrice* ed un *Vettore* e se proviamo a fare una somma:

In [ ]:
m+v

array([[13,  7, 14],
       [11,  9,  9],
       [16, 11, 13]])

Il modulo per poter fare questa operazione, è andato a replicare il vettore v nelle successive due righe create per poter sommare la matrice m.
Questa operazione è detta *Broadcasting*.


Anche per la matrici valgono gli stessi metodi visti con i vettori:



In [ ]:
m.sum()

55

In [ ]:
m

array([[4, 5, 9],
       [2, 7, 4],
       [7, 9, 8]])



*   *somma tra colonne*:




In [ ]:
m.sum(0)

array([13, 21, 21])

*   *somma tra righe*:

In [ ]:
m.sum(1)

array([18, 13, 24])

*   *Valore MAX tra colonne*:

In [ ]:
m.max(0)

array([7, 9, 9])

*   *Valore MAX tra righe*:

In [ ]:
m.max(1)

array([9, 7, 9])

*   *Valore MEDIO tra colonne*:

In [ ]:
m.mean(0)

array([4.33333333, 7.        , 7.        ])

*   *Valore MEDIO tra righe*:

In [ ]:
m.mean(1)

array([6.        , 4.33333333, 8.        ])

####***Generazione di Array***

Questo metodo da a disposizione anche tanti modi per creare Matrici/Vettori!

In [4]:
import numpy as np



*   *Matrici di Zeri*:




In [ ]:
m = np.zeros([3,3])
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


*   *Vettori di Zeri*:

In [ ]:
v=np.zeros([5])
v

array([0., 0., 0., 0., 0.])


*   *Matrici Diagonali*:

In [ ]:
d=np.eye(7,7)
d

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])


*   *Matrici\Vettori Generati Casualmente [0-1]*:


In [6]:
randomM=np.random.rand(4,4)
randomM

array([[0.71186821, 0.45370061, 0.8470907 , 0.79804733],
       [0.11642843, 0.71684916, 0.92574946, 0.60461277],
       [0.04403763, 0.53249436, 0.89741442, 0.64765879],
       [0.84441235, 0.4271484 , 0.70294143, 0.05786175]])

In [ ]:
randomV=np.random.rand(4)
randomV

array([0.43755936, 0.56327258, 0.91611699, 0.61968287])

*   *Matrici\Vettori Generati Casualmente Numeri Interi*:


In [ ]:
randomM=np.random.randint(6,size=[3,4])
print(randomM)

[[0 1 4 2]
 [5 0 3 3]
 [3 5 2 5]]


In [ ]:
randomV=np.random.randint(4,size=7)
randomV

array([0, 3, 1, 2, 2, 2, 3])

*   *Matrici\Vettori Generati Casualmente che seguono una distribuzione normale (media=0, dst=1)*:

In [ ]:
norm=np.random.normal(0,1,(3,3))
print(norm)

[[ 0.09763959  0.60650635  0.17488348]
 [ 0.91092094 -0.28754585 -0.67287159]
 [-0.67490132  0.12265652  0.2607307 ]]


In [ ]:
norm=np.random.normal(0,1,5)
print(norm)

[ 0.02747111  0.09777795 -2.15912414  0.12979723  0.38303788]


Sono funzioni che generano tutto casualmente e quindi ogni volta che le generiamo, questo saranno diverse!


Ma se volessimo che queste generazione random fossero in qualche modo fossero tali solo la prima volta:

In [ ]:
np.random.seed(1)
norm_1volta=np.random.rand(3,3)
print(norm_1volta)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


*   Vettori Generati Casualmente prendendo spunto da un 1-D Array 

In [13]:
a = [1,2,3,4]
np.random.choice(a, 5)

array([3, 4, 1, 1, 1])

*Genrazioni di Intevalli Numerici*:

Vediamo tra [0-10]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Vediamo da un valore di partenza a quello finale

In [ ]:
np.arange(3,17)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

* *Intervalli numeri di dimensione stabilita da noi, distribuiti uniformemente*: 

In [ ]:
np.linspace(0,10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10, num=20, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])



*   Generazione di array diretta con Input:




In [ ]:
vettore = np.array([input(.strip().split() for _ in range(1))], int)

####***Vettorizzazione***

Concludiamo il discorso su Numpy con questo discorso che ci permettono di effettuare diverse task senza chiamare ad esempio i *cicli for*!

Andiamo a vedere quanto può essere efficente rispetto alle normali procedure!




*   ES: andiamo calcolare in funzione del tempo alcuni compiti




In [ ]:
import numpy as np
import timeit as Timer

Creo un intervallo di un milione!

In [ ]:
m = np.arange(1000000)

Vado a creare una funzione che sommerà "1" ad ogni elemento della nostra sequenza!

Creo due funzioni che fanno quello che è stato prefissato e sopra 

In [ ]:
def loop_sum():
    return [val+1 for val in m]  

In [ ]:
timer_loop=min(Timer.repeat(repeat=10, number=10))

In [ ]:
def numpy_sum():
    return m+1

In [ ]:
timer_numpy=min(Timer.repeat(repeat=10, number=10))

Ora eseguiamo questa funzione 10 volte di fila andandola a cronometrare per tutte le dieci volte e scoprendo chi va piu lenta tra quelle piu veloci!

In [ ]:
print(timer_loop)
print(timer_numpy)

1.540000198474445e-07
3.000000106112566e-07


Possiamo vedere che con il modulo Numpy, lavori su indicizzazione sono piu veloci!!