<a href="https://colab.research.google.com/github/RoCkEtToMaN/Python/blob/master/Sezione_12_Il_Calcolo_Scientifico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Sezione 12: Il Calcolo Scientifico***

Il modulo che si vedrà è de-facto che darà vita a Scikit-Learn, Tensorflow, Pandas ed altri che vengono utilizzati in ambito ML e AI:



* *Numpy*


Se si usa Anaconda, questo modulo dovrebbe essere già installato!



```
pip install numpy
```






##***Calcolo Scientifico con Numpy***

Questo modulo è veramente calcolato ad hoc per questo, ha a disposizione molte funzioni fatte con C e quindi sono molto veloci!

Come tutti i moduli, lo importiamo:


In [3]:
import numpy as np

Ora affrontiamo a vedere i:

####***I Vettori***

Il calcolo tra vettori e matrici è un qualcosa molto importante in tutti i linguaggi di programmazione!

I vettori possono essere di piu dimensioni e di piu tipi!

In [4]:
l=[10,2,76,1,3]
v=np.array(l)

In [5]:
print(v,type(v))

[10  2 76  1  3] <class 'numpy.ndarray'>


Vediamo che è di tipo array!

Se vogliamo accedere agli indici, vale sempre il discorso dell'indexing!



*  *Indexing*:




In [ ]:
v[0]

10

In [ ]:
v[1]

2

In [ ]:
v[-1]

3



*   *Slicing*: per ritagliare una parte di array




In [ ]:
v[1:3]

array([ 2, 76])

In [ ]:
v[:1]

array([10])

In [ ]:
v[-1:]

array([3])



*   *Maschere*: andiamo a mascherare valori che non rispettano alcuni vincoli




In [6]:
mask = v >20

In [7]:
v
mask

array([False, False,  True, False, False])

In [8]:
v2=v[mask]
v2


array([76])

Questo passaggio lo si fa all'interno di un'unica operazione:

In [12]:
v_lm=v[v<v.mean()]
v_lm

array([10,  2,  1,  3])

Se volessimo modificare gli elementi di un vettore:

*   *Modificare* elementi di un vettore:




In [13]:
v=np.array([1,2,3,4,5])

In [14]:
v

array([1, 2, 3, 4, 5])

Come con le liste:

In [15]:
v[0]=10
v

array([10,  2,  3,  4,  5])

In [23]:
v[:2]


array([10,  2])

In [25]:
v[-2:]

array([4, 5])

In [27]:
v[:2]=v[-2:]
v

array([4, 5, 3, 4, 5])