<a href="https://colab.research.google.com/github/RoCkEtToMaN/Python/blob/master/Esercizi_Numpy_Calcolo_Scientifico_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Esercizi Numpy: Calcolo Scientifico***

##***Array Inverso***



*   In input una Lista di numeri

*   definire una funzione che Numpy inverta l'ordine degli elementi dell'array





*   ***Suggerimento***: possiamo definire un particolare tipo di array in questo modo con Numpy




In [ ]:
import numpy as np

a = np.array([1,2,3], float)
print(a)

In [ ]:
import numpy as np

def npInvert(array):

     
     array_int = np.array(array, float)
     array_inv = array_int[::-1]
     

     return print(array_inv)

In [48]:
In = input("Inserire i valori dell'array: ").split()

npInvert(In)

Inserire i valori dell'array: 1 2
[2. 1.]


##***Shape e Reshape***



*   Acquisire in input una lista di 9 num interi
*   Convertire la lista in un vettore 3x3


Credo una shape di in e poi reshap la modello




In [66]:
import numpy as np

def Re_shape(array):     

    array = np.array(array, int)   
     
    return print(array.reshape(3,3))
    

In [67]:
In = input("Inserire i valori dell'array: ").split()

Re_shape(In)

Inserire i valori dell'array: 1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##***Transpose and Flatten***



*   Acquisisci in input due numeri N, M
*   Acquisisci in input N righe con M interi ed utilizzarli per creare una matrice Numpy
*   Stampa la matrice Trasposta
*   Stampa la matrice Flatten





* N.B. la matrice Trasposta con np la si ottiene con ".transpose()"



In [119]:
import numpy as np

def TranFlat(N,M):     
    randomM=np.random.randint(M + 1,size=[N,M])
    randomT=np.transpose(randomM)
    randomF=randomT.reshape(1,randomT.size) 
     
    return print("Trasposta:\n "+ str(randomT)), print("\nFlatten:\n "+ str(randomF))

In [121]:
import numpy as np

def TranFlat2(N,M):     
    randomM=np.random.randint(M + 1,size=[N,M])
         
    return print("Trasposta:\n "+ str(randomM.transpose())), print("\nFlatten:\n "+ str(randomM.flatten()))

In [122]:
N = int(input("Inserire N: "))
M = int(input("Inserire M: "))
TranFlat2(N,M)

Inserire N: 4
Inserire M: 5
Trasposta:
 [[5 5 2 3]
 [4 0 1 1]
 [2 3 5 2]
 [0 4 5 3]
 [3 3 0 3]]

Flatten:
 [5 4 2 0 3 5 0 3 4 3 2 1 5 5 0 3 1 2 3 3]


(None, None)

##***Aritmetica degli Array***




*   Acquisisci due numeri N, M in input
*   Acquisisci in input N righe con M interi ed utilizzarli per creare una matrice Numpy A
*   Acquisisci in input N righe con M interi ed utilizzarli per creare una matrice Numpy B
*   somma tra le matrici
*    differenza tra le matrici
*   prodotto tra le matrici
*   divisione tra interi tra le matrici
*   modulo tra le matrici
*   A elevata a B









In [2]:
import numpy as np

def Aritmetica(N,M):

    A=np.random.randint(M + 1,size=[N,M])
    B=np.random.randint(M + 1,size=[N,M])

    print("A: \n"+str(A))
    print("B: \n"+str(B))
    print("Somma: \n"+str(A+B))
    print("Differenza: \n"+str(A-B))  
    print("Prodotto: \n"+str(A*B)) 
    print("Divisione: \n"+str(A/B)) 
    print("Divisione per Interi: \n"+str(A//B)) 
    print("Modulo: \n"+str(A%B)) 
    print("Potenza: \n"+str(A**B)) 

In [4]:
N = int(input("Inserire N: "))
M = int(input("Inserire M: "))
Aritmetica(N,M)

Inserire N: 2
Inserire M: 3
A: 
[[2 1 0]
 [3 1 1]]
B: 
[[1 1 1]
 [3 2 2]]
Somma: 
[[3 2 1]
 [6 3 3]]
Differenza: 
[[ 1  0 -1]
 [ 0 -1 -1]]
Prodotto: 
[[2 1 0]
 [9 2 2]]
Divisione: 
[[2.  1.  0. ]
 [1.  0.5 0.5]]
Divisione per Interi: 
[[2 1 0]
 [1 0 0]]
Modulo: 
[[0 0 0]
 [0 1 1]]
Potenza: 
[[ 2  1  0]
 [27  1  1]]
